# Project
project_name: "Wide Res Net"
save_dir: "./experiments"
torchscript_model_save_path: "./experiments/"
seed: 9423

# Data
dataset: "CIFAR10"
data_dir: "./data"
image_channels: 3
num_classes: 10
image_size: 64

# Training
depth: 40
K: 10
dropout_rate: 0.5
log_every_n_steps: 10
lr: 0.1
epochs: 200
batch_size: 128
weight_decay: 0.0005
lr_scheduler_gamma: 0.2
momentum: 0.9
precision: 16
gradient_clip_val: 2
accumulate_grad_batches: 2
