project_name: 'MobileNetV2'
save_dir: './experiments'
dataset: 'CIFAR10'
data_dir: './data'
torchscript_model_save_path: './experiments/'
seed: '2022'

image_size: 224
image_channels: 3
n_classes: 10

hparams:
  {
    lr: 0.1,
    epochs: 200,
    batch_size: 64,
    alpha: 1.0,
    rho: 1.0
  }