# Project
project_name: "Xception"
save_dir: "./experiments"
torchscript_model_save_path: "./experiments/"
seed: 9423

# Data
dataset: "CIFAR10"
data_dir: "./data"
image_channels: 3
num_classes: 10
image_size: 299

# Training

log_every_n_steps: 10
lr: 0.045
epochs: 100
batch_size: 128
weight_decay: 1.0e-3
lr_scheduler_gamma: 0.94
scheduler_frequency: 2
scheduler_interval: epoch
momentum: 0.9
precision: 16
gradient_clip_val: Null
accumulate_grad_batches: 2
