# Project
project_name: 'EfficientNetV1'
save_dir: './experiments'
torchscript_model_save_path: './experiments/'
seed: '2022'

# Data
dataset: 'CIFAR10'
data_dir: './data'
image_channels: 3
n_classes: 10

# Hyper-parameter
lr: 0.01
epochs: 200
batch_size: 32
weight_decay: 0.0
dropout_rate: 0.5
scheduler_factor: 0.1
scheduler_patience: 3
earlystopping_patience: 6

# Model type
model_size: 'b0'
model_type:
    b0: [1.0, 1.0, 224]
    b1: [1.0, 1.1, 240]
    b2: [1.1, 1.2, 260]
    b3: [1.2, 1.4, 300]
    b4: [1.4, 1.8, 380]
    b5: [1.6, 2.2, 456]
    b6: [1.8, 2.6, 528]
    b7: [2.0, 3.1, 600]
