project_name: "VGG"
model: "11"
save_dir: "./experiments"
dataset: "CIFAR10"
data_dir: "./data"
torchscript_model_save_path: "./experiments/"
seed: 9423

image_channals: 3
n_classes: 10
image_size: 224

hparams:
  { model_type: "VGG11", lr: 0.005, epochs: 100, batch_size: 32, use_bn: true }
