project_name: "Inception V3"
save_dir: "./experiments"
dataset: "CIFAR10"
data_dir: "./data"
torchscript_model_save_path: "./experiments/"
seed: 9423

image_channels: 3
n_classes: 10
image_size: 299

hparams:
  {
    norm: true,
    lr: 0.01,
    epochs: 100,
    batch_size: 64,
    label_smoothing: 0.1,
    weight_decay: 0.9,
    momentum: 0.9,
    eps: 1.0,
    lr_exponential_rate: 0.94,
    gradient_clipping: 2.0,
    loss_weight: 0.5,
    aux_loss_weight: 0.5,
    precision: 32,
  }
