project_name: "LeNet5"
save_dir: "./experiments"
dataset: "FashionMNIST"
data_dir: "./data"
torchscript_model_save_path: "./experiments/LeNet-5.pt"
seed: 9423

image_channals: 1

hparams: { lr: 0.005, epochs: 256, batch_size: 512 }
