project_name: 'MobileNetV1'
save_dir: './experiments'
dataset: 'CIFAR10'
data_dir: './data'
torchscript_model_save_path: './experiments/'
seed: '2022'

image_size: 224
image_channels: 3
n_classes: 10
alpha: 1.0
rho: 1.0

hparams:
  {
    lr: 0.03,
    epochs: 200,
    batch_size: 64
  }